# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MealSavvy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealSavvy

      pod 'IQKeyboardManagerSwift'
      pod 'Alamofire'
      pod 'AlamofireObjectMapper'
      pod 'GoogleMaps'
      pod 'SwiftyJSON'
      pod 'GooglePlaces'
      pod 'GoogleSignIn'
        pod 'GooglePlacePicker'
      pod 'FBSDKLoginKit'
      pod 'SlideMenuControllerSwift'
      pod 'AlamofireImage'
      pod 'SwipeBack'
      pod 'CircleProgressBar'
      pod 'Socket.IO-Client-Swift'
      pod ‘UITextView+Placeholder’
      pod 'CommonCryptoModule'
      pod 'SVProgressHUD'
      pod 'DateToolsSwift'
      pod 'Kingfisher'
      
            
      # Issue with IBDesignable: https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098
      post_install do |installer|
          installer.pods_project.build_configurations.each do |config|
              config.build_settings.delete('CODE_SIGNING_ALLOWED')
              config.build_settings.delete('CODE_SIGNING_REQUIRED')
          end
      end

  target 'MealSavvyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MealSavvyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
